# Generated by Django 5.1.4 on 2024-12-11 18:20

import common.articles.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        max_length=256,
                        unique=True,
                        validators=[common.articles.validators.TitleValidator()],
                    ),
                ),
                (
                    "content",
                    models.FileField(
                        upload_to=common.articles.validators.UploadToValidator()
                    ),
                ),
                ("slug", models.SlugField(blank=True, max_length=200, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Article",
                "verbose_name_plural": "Articles",
                "db_table": "common_articles",
                "ordering": ["created_at"],
            },
        ),
    ]
